import React, { useState, useEffect } from "react";
import {
  Plus,
  Edit,
  Trash2,
  X,
  Phone,
  Mail,
  MapPin,
  Clock,
  Globe,
  Facebook,
  MessageCircle,
  Music,
} from "lucide-react";
import { useForm, Controller } from "react-hook-form";
import { useContactStore, type Company } from "@/store/zustand/contactStore";
import { LoadingOverlay } from "./LoadingOverlay";
import { AdminNotification, useAdminNotification } from "./AdminNotification";

type CompanyFormValues = {
  name_th: string;
  name_en: string;
  address_th: string;
  address_en: string;
  tel: string;
  email: string;
  business_hour_th?: string;
  business_hour_en?: string;
};

export const ContactManager = () => {
  const [activeTab, setActiveTab] = useState("primary");

  const { notification, hideNotification, showSuccess, showError } =
    useAdminNotification();
  const {
    contactInfo,
    companies,
    loading,
    error,
    success,
    fetchContactInfo,
    fetchCompanies,
    updateContactInfo,
    addCompany,
    updateCompany,
    deleteCompany,
    clearMessages,
  } = useContactStore();

  useEffect(() => {
    fetchContactInfo();
    fetchCompanies();
  }, [fetchContactInfo, fetchCompanies]);

  const [modalState, setModalState] = useState<{
    isOpen: boolean;
    type: "" | "add" | "edit" | "delete";
    selectedCompany: Company | null;
  }>({
    isOpen: false,
    type: "",
    selectedCompany: null,
  });

  // Form control for company modal
  const { control, handleSubmit, reset, setValue } = useForm<CompanyFormValues>(
    {
      defaultValues: {
        name_th: "",
        name_en: "",
        address_th: "",
        address_en: "",
        tel: "",
        email: "",
        business_hour_th: "",
        business_hour_en: "",
      },
    }
  );

  // React Hook Form for primary contact
  type ContactFormValues = {
    tel: string;
    email: string;
    facebook: string;
    line: string;
    tiktok: string;
    google_map_url: string;
    business_hour_th: string;
    business_hour_en: string;
  };

  const {
    control: contactControl,
    handleSubmit: handleContactSubmit,
    setValue: setContactValue,
  } = useForm<ContactFormValues>({
    defaultValues: {
      tel: "",
      email: "",
      facebook: "",
      line: "",
      tiktok: "",
      google_map_url: "",
      business_hour_th: "",
      business_hour_en: "",
    },
  });

  // Populate form when contactInfo is loaded
  useEffect(() => {
    if (contactInfo) {
      setContactValue("tel", contactInfo.tel || "");
      setContactValue("email", contactInfo.email || "");
      setContactValue("facebook", contactInfo.facebook || "");
      setContactValue("line", contactInfo.line || "");
      setContactValue("tiktok", contactInfo.tiktok || "");
      setContactValue("google_map_url", contactInfo.google_map_url || "");
      setContactValue("business_hour_th", contactInfo.business_hour_th || "");
      setContactValue("business_hour_en", contactInfo.business_hour_en || "");
    }
  }, [contactInfo, setContactValue]);

  // Sync form with contactInfo
  useEffect(() => {
    if (contactInfo) {
      setContactValue("tel", contactInfo.tel || "");
      setContactValue("email", contactInfo.email || "");
      setContactValue("facebook", contactInfo.facebook || "");
      setContactValue("line", contactInfo.line || "");
      setContactValue("tiktok", contactInfo.tiktok || "");
      setContactValue("google_map_url", contactInfo.google_map_url || "");
      setContactValue("business_hour_th", contactInfo.business_hour_th || "");
      setContactValue("business_hour_en", contactInfo.business_hour_en || "");
    }
  }, [contactInfo, setContactValue]);

  // Modal functions
  const openCompanyModal = (
    type: "add" | "edit" | "delete",
    company?: Company
  ) => {
    setModalState({
      isOpen: true,
      type,
      selectedCompany: company || null,
    });

    if (type === "edit" && company) {
      setValue("name_th", company.name_th);
      setValue("name_en", company.name_en);
      setValue("address_th", company.address_th);
      setValue("address_en", company.address_en);
      setValue("tel", company.tel);
      setValue("email", company.email);
      setValue("business_hour_th", company.business_hour_th || "");
      setValue("business_hour_en", company.business_hour_en || "");
    } else if (type === "add") {
      reset();
    }
  };

  const closeCompanyModal = () => {
    setModalState({
      isOpen: false,
      type: "",
      selectedCompany: null,
    });
    reset();
  };

  const onSubmitCompany = async (data: CompanyFormValues) => {
    try {
      if (modalState.type === "add") {
        // For add, we don't need to include id as it will be generated by the server
        const companyData = { ...data }; // Temporary id, will be replaced by server
        await addCompany(companyData);
      } else if (modalState.type === "edit" && modalState.selectedCompany?.id) {
        // For edit, we include the existing id
        const companyData = { ...data, id: modalState.selectedCompany.id };
        await updateCompany(modalState.selectedCompany.id, companyData);
        //alert("Company updated successfully!");
      }
      closeCompanyModal();
      // Refresh the companies list
      setTimeout(() => fetchCompanies(), 100);
    } catch (error) {
      console.error("Error saving company:", error);
    }
  };

  const handleDeleteCompany = async () => {
    if (modalState.selectedCompany?.id) {
      try {
        await deleteCompany(modalState.selectedCompany.id);
        closeCompanyModal();
        // Refresh the companies list
        setTimeout(() => fetchCompanies(), 100);
      } catch (error) {
        console.error("Error deleting company:", error);
      }
    }
  };

  const onSubmitContact = async (data: ContactFormValues) => {
    if (contactInfo?.id) {
      try {
        await updateContactInfo({
          ...contactInfo,
          ...data,
        });
      } catch (error) {
        console.error("Error updating contact info:", error);
      }
    }
  };

  // Handle success and error messages
  React.useEffect(() => {
    if (success) {
      showSuccess("สำเร็จ", success);
      clearMessages();
    }
    if (error) {
      showError("เกิดข้อผิดพลาด", error);
      clearMessages();
    }
  }, [success, error, clearMessages, showSuccess, showError]);

  return (
    <div className="space-y-6 relative">
      {loading && <LoadingOverlay />}

      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold text-gray-900">Contact Manager</h2>
      </div>

      {/* Tab Navigation */}
      <div className="bg-white rounded-lg shadow-sm border">
        <div className="border-b border-gray-200">
          <nav className="flex space-x-8 px-6">
            <button
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === "primary"
                  ? "border-blue-500 text-blue-600"
                  : "border-transparent text-gray-500 hover:text-gray-700"
              }`}
              onClick={() => setActiveTab("primary")}>
              Primary Contact
            </button>
            <button
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === "companies"
                  ? "border-blue-500 text-blue-600"
                  : "border-transparent text-gray-500 hover:text-gray-700"
              }`}
              onClick={() => setActiveTab("companies")}>
              Partner Companies
            </button>
          </nav>
        </div>

        <div className="p-6">
          {activeTab === "primary" ? (
            <form
              className="space-y-6"
              onSubmit={handleContactSubmit(onSubmitContact)}>
              <h3 className="text-lg font-semibold text-gray-900">
                Primary Contact Information
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <Controller
                    name="tel"
                    control={contactControl}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          <Phone className="inline w-4 h-4 mr-1" />
                          Phone Number
                        </label>
                        <input
                          type="tel"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Phone number"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                  <Controller
                    name="email"
                    control={contactControl}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          <Mail className="inline w-4 h-4 mr-1" />
                          Email
                        </label>
                        <input
                          type="email"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Email"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                  <Controller
                    name="facebook"
                    control={contactControl}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          <Facebook className="inline w-4 h-4 mr-1" />
                          Facebook
                        </label>
                        <input
                          type="url"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Facebook"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                  <Controller
                    name="business_hour_th"
                    control={contactControl}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          {`เวลาทำการ (ไทย)`}
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Business Hours"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                </div>
                <div className="space-y-4">
                  <Controller
                    name="line"
                    control={contactControl}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          <MessageCircle className="inline w-4 h-4 mr-1" />
                          Line ID
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Line ID"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                  <Controller
                    name="tiktok"
                    control={contactControl}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          <Music className="inline w-4 h-4 mr-1" />
                          TikTok
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="TikTok"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                  <Controller
                    name="google_map_url"
                    control={contactControl}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          <Globe className="inline w-4 h-4 mr-1" />
                          Google Maps URL
                        </label>
                        <input
                          type="url"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Google Maps URL"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />

                  <Controller
                    name="business_hour_en"
                    control={contactControl}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          {`Business Hours (EN)`}
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Business Hours"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                </div>
              </div>

              {/* Save Changes Button for Primary Contact */}
              <div className="flex justify-end pt-6 border-t border-gray-200">
                <button
                  type="submit"
                  className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 flex items-center gap-2">
                  Save Primary Contact
                </button>
              </div>
            </form>
          ) : (
            <div className="space-y-6">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-gray-900">
                  Partner Companies
                </h3>
                <button
                  onClick={() => openCompanyModal("add")}
                  className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 flex items-center gap-2">
                  <Plus size={16} />
                  Add Company
                </button>
              </div>

              <div className="grid gap-4">
                {(companies || []).map((company) => (
                  <div
                    key={company.id}
                    className="border border-gray-200 rounded-lg p-4 hover:bg-gray-50">
                    <div className="flex items-start justify-between">
                      <div className="flex-1 space-y-2">
                        <h4 className="font-medium text-gray-900">
                          {company.name_en}
                        </h4>
                        <div className="text-sm text-gray-600 space-y-1">
                          <p className="flex items-center gap-2">
                            <MapPin size={14} />
                            {company.address_en}
                          </p>
                          <p className="flex items-center gap-2">
                            <Phone size={14} />
                            {company.tel}
                          </p>
                          <p className="flex items-center gap-2">
                            <Mail size={14} />
                            {company.email}
                          </p>
                          <p className="flex items-center gap-2">
                            <Clock size={14} />
                            {company.business_hour_en}
                          </p>
                        </div>
                      </div>
                      <div className="flex gap-2 ml-4">
                        <button
                          onClick={() => openCompanyModal("edit", company)}
                          className="text-blue-600 hover:text-blue-700 p-1">
                          <Edit size={16} />
                        </button>
                        <button
                          onClick={() => openCompanyModal("delete", company)}
                          className="text-red-600 hover:text-red-700 p-1">
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Company Modal */}
      {modalState.isOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl mx-4 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">
                {modalState.type === "add" && "Add Company"}
                {modalState.type === "edit" && "Edit Company"}
                {modalState.type === "delete" && "Delete Company"}
              </h3>
              <button
                onClick={closeCompanyModal}
                className="text-gray-400 hover:text-gray-600">
                <X size={20} />
              </button>
            </div>

            {modalState.type === "delete" ? (
              <div className="space-y-4">
                <p className="text-gray-600">
                  Are you sure you want to delete &ldquo;
                  {modalState.selectedCompany?.name_en}&rdquo;? This action
                  cannot be undone.
                </p>
                <div className="flex justify-end gap-3">
                  <button
                    onClick={closeCompanyModal}
                    className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
                    Cancel
                  </button>
                  <button
                    onClick={handleDeleteCompany}
                    className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700">
                    Delete
                  </button>
                </div>
              </div>
            ) : (
              <form
                onSubmit={handleSubmit(onSubmitCompany)}
                className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Controller
                    name="name_th"
                    control={control}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Company Name (TH)
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="ชื่อบริษัท"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                  <Controller
                    name="name_en"
                    control={control}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Company Name (EN)
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Company name"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Controller
                    name="address_th"
                    control={control}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Address (TH)
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="ที่อยู่บริษัท"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                  <Controller
                    name="address_en"
                    control={control}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Address (EN)
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Company address"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Controller
                    name="tel"
                    control={control}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Phone Number
                        </label>
                        <input
                          type="tel"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="+66 2 xxx xxxx"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                  <Controller
                    name="email"
                    control={control}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Email
                        </label>
                        <input
                          type="email"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="company@email.com"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Controller
                    name="business_hour_th"
                    control={control}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Business Hours (TH)
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="เวลาทำการ"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                  <Controller
                    name="business_hour_en"
                    control={control}
                    render={({ field }) => (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                          Business Hours (EN)
                        </label>
                        <input
                          type="text"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                          placeholder="Business hours"
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </div>
                    )}
                  />
                </div>

                <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
                  <button
                    type="button"
                    onClick={closeCompanyModal}
                    className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
                    {modalState.type === "add" ? "Add Company" : "Save Changes"}
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      )}

      {/* Notification */}
      {notification && (
        <AdminNotification
          type={notification.type}
          title={notification.title}
          message={notification.message}
          isVisible={notification.isVisible}
          onDismiss={hideNotification}
        />
      )}
    </div>
  );
};
